### ISSUE TITLE
Trojan下无法使用webtest获取延迟数据

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#10]
ss-webtest.sh 也没搞明白，老大研究下
![image](https://user-images.githubusercontent.com/31977161/79180324-404ac180-7e3c-11ea-9a9d-e38f646c06a0.png)

**Comment by idealism-xxm** [comment]
这里没改过，不知道是不是没有兼容的问题，我有空研究以下。
因为原来其他模式也有这种情况，部分有测速结果，部分失败。

**Comment by babylife** [comment]
好的 我有空也研究下
