### ISSUE TITLE
该如何修改样式或者格式让这个别名地址完整显示成，但是又不影响其他栏的显示

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#12]
![image](https://user-images.githubusercontent.com/31977161/79209040-78bac180-7e75-11ea-889e-f07d53cfcde8.png)

**Comment by idealism-xxm** [comment]
原来的宽度配置还挺合适的，感觉没必要改样式（通过换行显示的话就会比其他的高十几 px ）。
可以考虑使用 `hover` 的形式。

**Comment by babylife** [comment]
> 原来的宽度配置还挺合适的，感觉没必要改样式（通过换行显示的话就会比其他的高十几 px ）。
> 
> 可以考虑使用 `hover` 的形式。

您说的有道理 鼠标上去直接显示 完美！ 不过我对asp代码不熟悉，不知道如何修改，大神方便的话下个版本一起做了？ 想必应该不难 哈哈
