### ISSUE TITLE
补充疑问

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#13]
我在替换好Main_Ss_Content.asp后已经正常，真准备替换Main_Ss_LoadBlance.asp的时候发现这里本来就是可以正常显示的，以一格显示两行的方式，大佬指点下这个是怎么做到的？补充个对比图
![image](https://user-images.githubusercontent.com/31977161/79308373-0d332b80-7f2b-11ea-9dfc-5c832d196d91.png)
![image](https://user-images.githubusercontent.com/31977161/79309186-7b2c2280-7f2c-11ea-81b9-4eaf5efb82d3.png)

**Comment by idealism-xxm** [comment]
样式的问题比较简单就能实现，研究一下 `css` 就知道了。
这两种展示形式的差别主要是 `overflow`, `white-space`, `text-overflow` 这三种属性设置了不同值。
