### ISSUE TITLE
BUG: trojan订阅地址时，如果地址别名包含空格，则订阅事件导致整个插件无法加载

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#15]
最近Trojan订阅地址更新了，看了下机场的地址别名由原来的中文改写了英文，但是个别地址有英文空格，导致整个插件崩溃了，订阅完成之后整个插件都无法在WEB上控制。 

我是通过SS PLUS的订阅发现这些地址的别名显示异常，所以猜测是这个原因，机场本来的节点别名显示中文没有这个问题，请大佬看看代码侧是否可以优化下，我这可以配合测试，谢谢！

![image](https://user-images.githubusercontent.com/31977161/79945621-c2706100-84a0-11ea-9b97-707b11253ee4.png)

**Comment by babylife** [comment]
联系机场改写成中文别名后解决，老大觉得没必要修的话可以关闭

**Comment by idealism-xxm** [comment]
别名含有空格的已经在这个 [commit](https://github.com/idealism-xxm/fancyss/commit/8cdfd69fc6879f455587ddefb297fed83a669c6f#diff-437c825108ae4fd764d018171f439510R777) 中处理过了

还有空白字符的情况有可能是 `\t` ，可以本地直接拿到订阅的内容，解码后看看是不是含有奇怪的字符

**Comment by babylife** [comment]
好的 ，可能是这个sh文件我没有在本地更新，解码后看过就是一个空格
