### ISSUE TITLE
升级代码逻辑小BUG

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#18]
今天想升级 结果发现判断版本代码有个问题，由于我的网络网络问题，无法访问下载地址，后来浏览器访问升级链接的版本文件， 显示报错500 internel server error。 我发现代码检测用500来作为新版本号来判断和当期本地版本是否一致，当不同的时候直接下载更新。 然后问题又来了 因为无法下载文件 导致不停的retry，也不知道如何去停止。
希望大侠可以加个判断验证版本信息。还有升级文件下载失败是否可以重试多次后自动退出？
![image](https://user-images.githubusercontent.com/31977161/80161671-b8b33e80-8603-11ea-9e8a-d83f3fbfaa68.png)

**Comment by babylife** [comment]
if [ "$ss_basic_version_local" != "$ss_basic_version_web1" ];then
		echo_date 主服务器在线版本号："$ss_basic_version_web1" 和本地版本号："$ss_basic_version_local" 不同！

这个代码是否应该想判断下版本格式，比如是X.X.X， 然后判断版本大小？

**Comment by idealism-xxm** [comment]
`wget` 默认重试 20 次，不会无限重试。目前来说，获取到的版本都是最新的，而本地的版本必定不会再新，所以没必要判断。

**Comment by babylife** [comment]
好的
