### ISSUE TITLE
解析的Trojan节点无法保存

### ISSUE THREAD

**Issue by ywc416** [idealism-xxm/fancyss#21]
路由器固件是梅林380.70_0-X7.9.1，科学上网插件是最新版本。
问题状况：Trojan节点是通过解析并保存，使用正常，并且和订阅的V2ray和SSR都可以正常使用，但是一但在更新管理的订阅节点里点击保存并订阅更新后，Trojan节点就丢失了，需要再次在解析并保存里手动添加，V2ray和SSR的节点无此问题，麻烦能够修复一下，谢谢！

**Comment by idealism-xxm** [comment]
@ywc416 我这里怎么都复现不了，可以先确认以下几点帮助排查：
- 你那里只要按照你说的的操作方式就一定能够复现么？
- 删除节点的逻辑与其类型应该是无关的，可以试一下换个别的非订阅链接中的其他类型的节点试试看能复现么？
- 复现的时候顺便看看跳转到 节点管理 这个 tab 时，请求的数据，里面订阅的节点和会丢失节点的 group 分别是什么？

**Comment by ylp8533** [comment]
我也有类似的问题，通过trojan订阅链接可以刷出节点但是无论选择哪个节点都无法翻墙，但只要通过手动添加trojan节点就可以翻墙成功，不知是哪里出了问题，希望能够修复一下，万分感谢！

**Comment by ywc416** [comment]
我这可以复现问题，不知道是不是节点的问题，你也可以试一下。

**Comment by idealism-xxm** [comment]
@ywc416 应该是解析出来对别名消失了，所以订阅后会有问题。
暂时解决方法：给所有空白别名的结点加上别名，以后订阅就不会消失了。
下次更新版本后应该就会修复。

【注意】你的 trojan 链接已经泄漏了，可想办法处理一下，最好编辑一下那个回复消除，并更新链接。
