### ISSUE TITLE
替换为dnsmasq-fastlookup之后 ，无法翻墙

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#22]
不知道具体问题在哪里，大佬看看
![image](https://user-images.githubusercontent.com/31977161/80449460-ca714a80-8951-11ea-8f73-6d14a76dc458.png)

**Comment by idealism-xxm** [comment]
[nsmasq-fastlookup在384.15无法使用](https://github.com/hq450/fancyss/issues/830) 看起来像是这个问题？

**Comment by babylife** [comment]
估计是的 算了 研究也是被弃用的节奏
