### ISSUE TITLE
压缩包太大，WS880离线安装失败

### ISSUE THREAD

**Issue by ultraboy** [idealism-xxm/fancyss#23]
ssh上去看到是因为安装包太大，解压到/tmp的时候空间不够了。手动暂时把压缩包移动到jffs分区，解压然后删除压缩包再执行install.sh安装成功。

**Comment by idealism-xxm** [comment]
能安装成功就行😂，空间太小即使把压缩包搞更小还是会出现。推荐没问题就使用当前版本，或者 fork 后删除不必要的 bin ，自定义打包。
