### ISSUE TITLE
使用trojan订阅地址，可以刷出节点但无法翻墙~

### ISSUE THREAD

**Issue by ylp8533** [idealism-xxm/fancyss#24]
路由器：AC66UB1 固件：380.70_0-X7.9.1 插件版本：4.3.4
使用中发现一个问题，通过trojan订阅链接可以刷出节点，可是无论选择哪个节点都无法翻墙，但只要通过手动添加trojan节点就可以翻墙成功（v2ray没有此问题）。不知是哪里出了问题，希望能够修复一下，万分感谢！

**Comment by idealism-xxm** [comment]
@ylp8533 理论上来说应该不会是本身的问题，更有可能是订阅链接的问题。可以先确认以下几点帮助排查：
- 使用订阅节点后，页面上输出的各项关键日志，各个组件是否成功启动？
- 编辑订阅后的节点，查看各项是否含有奇怪的字符，并可以手动使用这些信息新建一个节点，看是否能够成功？
- 更细致的排查：访问订阅链接 - base64 解码 - 查看是否有问题

**Comment by ylp8533** [comment]
> @ylp8533 理论上来说应该不会是本身的问题，更有可能是订阅链接的问题。可以先确认以下几点帮助排查：
> 
> * 使用订阅节点后，页面上输出的各项关键日志，各个组件是否成功启动？
> * 编辑订阅后的节点，查看各项是否含有奇怪的字符，并可以手动使用这些信息新建一个节点，看是否能够成功？
> * 更细致的排查：访问订阅链接 - base64 解码 - 查看是否有问题

谢谢回复，找到问题所在了，原来在订阅链接后，端口后面会出现一些奇怪的字符，删除多余字符后问题就决绝了！非常感谢！
