### ISSUE TITLE
小咨询 ：haproxy 模块还会更新吗？

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#25]
大神您好！
虽然当前版本没有问题 ，但是新版本距离当前版本已经一年多了。不知道当前是否还可以编译到ARM380的梅林上，请大神指教
haproxy			1.8.8 		2018年05月03日编译

http://www.haproxy.org/
November 25th, 2019 : HAProxy 2.1.0 is out!

**Comment by babylife** [comment]
![image](https://user-images.githubusercontent.com/31977161/81133016-f066a280-8f82-11ea-81ae-929daeafc807.png)
补充貌似1.8.x比较合适

**Comment by babylife** [comment]
https://github.com/rampageX/arm-static-bins/tree/master/haproxy
请大佬看看，我这也准备测试

**Comment by idealism-xxm** [comment]
trojan 使用起来很稳，我都没切过节点😂不过可以更新一下。我没用负载均衡，你可以看看使用哪一版本

**Comment by babylife** [comment]
好的， 我测试几天再反馈给你，我倒是一直用HA的，因为机场的某些trojan节点也有不稳定的时候

**Comment by babylife** [comment]
https://github.com/rampageX/arm-static-bins/tree/master/haproxy/1.8.25/lite
大神我使用1.8.25的lite版本一周十分稳定，可以考虑收入
