### ISSUE TITLE
订阅以后提示节点错误

### ISSUE THREAD

**Issue by suemyass** [idealism-xxm/fancyss#27]

**Comment by suemyass** [comment]
实测 K3,R7000,R7900,R8000 都这样

**Comment by idealism-xxm** [comment]
@suemyass 通过你图中的订阅链接，我已经找到问题了（我已经手动帮把你的图片删掉了，以免泄漏，不过最好还是重新生成一下链接）

你的订阅链接包含多种类型的节点，但目前代码不支持混合类型的订阅方式😂目前已优先处理 trojan 节点，其他节点是展示信息的，暂时先忽略了
