### ISSUE TITLE
[更新管理] 无法更新新的规则

### ISSUE THREAD

**Issue by cutsin** [idealism-xxm/fancyss#30]
一直报：

```
开始更新shadowsocks规则，请等待...
没有检测到在线版本，可能是访问github有问题，去大陆白名单模式试试吧！
```

但改哪个模式都不行，重启也不行。
版本：
R8500 - 380.70_0-X7.9.1
fancyss_arm 4.3.7

**Comment by idealism-xxm** [comment]
我这边的是可以的，怀疑还是开了后导致无法访问 github 引起的，可以看看“运行状态”部分，两个是否都能正常工作，再在浏览器里访问一下看看是否能访问。

最近 “DNS 设定” -> “节点域名解析DNS服务器” 选自带的好像不能成功解析节点，换成 `8.8.8.8` 就能成功解析并正常访问

**Comment by cutsin** [comment]
噢还真是DNS问题，勾选“https_dns_proxy”就不行，一直以为这样比较好……
多谢！
