### ISSUE TITLE
koolshare软件中心1.4.6提示包含非法关键词

### ISSUE THREAD

**Issue by suemyass** [idealism-xxm/fancyss#31]
估计是koolshare在压力下修改了安装方式，安装时提示根据法律规定，软件中心不会安装此插件，更改插件名称不管用

**Comment by wekingchen** [comment]
把这个脚本替换回旧版试试 /jffs/.koolshare/scripts/ks_tar_intall.sh

这是旧版链接：
https://raw.githubusercontent.com/koolshare/koolshare.github.io/285e91b107e8c20c7ad2a74748e7d18c03cae510/softcenter/softcenter/scripts/ks_tar_intall.sh

**Comment by wekingchen** [comment]
还有一个方法：开启路由器的SSH功能，登录并输入以下命令后，再进行离线安装。

sed -i 's/\tdetect_package/\t# detect_package/g' /koolshare/scripts/ks_tar_install.sh
