### ISSUE TITLE
更新gfwlist和白名单CDN都显示无法获取最新版本

### ISSUE THREAD

**Issue by TrueBoy** [idealism-xxm/fancyss#33]
插件版本4.3.7，确定可以科学上网，用全局或者白名单模式更新名单也是显示无法获取最新版本，但点日期是可以看到名单有更新的。。目前显示的名单是22 Mar的，最新应该是5月的。

**Comment by idealism-xxm** [comment]
我点了一下就全部更新了😂用的大陆白名单模式，dns 是 8.8.8.8

**Comment by TrueBoy** [comment]
> 我点了一下就全部更新了😂用的大陆白名单模式，dns 是 8.8.8.8

谢谢！我吧dns从dns_proxy改为chinadns就好了。。。谢谢提醒！
