### ISSUE TITLE
Trojan已经更新1.16 请大佬更新

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#36]
https://github.com/rampageX/arm-static-bins/blob/master/trojan/1.16.0/trojan

**Comment by vickiegpt** [comment]
自己clone下来run一遍脚本就行。不用麻烦大佬。

**Comment by babylife** [comment]
发现1.16的文件似乎有问题，开启了HA之后，就无法关闭主进程，导致单独切换文件有问题，换回来之后正常
