### ISSUE TITLE
一个非常奇怪的问题

### ISSUE THREAD

**Issue by babylife** [idealism-xxm/fancyss#39]
最近想使用某个节点直接链接，发现所有节点都无法正常使用，但是使用HAPROXY的情况下，都没有问题，节点本身是好的，用电脑手机都OK。 所有大招都用了还是不行，有什么建议吗大侠？

**Comment by hilobekerfulaisien** [comment]
希望大佬能吧这个插件支持openwrt, openwrt支持超级多的路由，很多插件都围绕梅林转， 实在是太折腾了。

**Comment by babylife** [comment]
已经定位是最新版本trojan的问题
